### PR TITLE
really drop python<=3.7 support

### PR DESCRIPTION
**Pull request by kloczek**
Filter all code over `pyupgrade --py38-plus`.

### CODE REVIEW

**Comment by kloczek** [comment]
My PR not messed with that line on which point plint
image

**Comment by brunato** [comment]
Sorry but too many changes in so many files to be merged in the master branch. 
Also I agree with some changes (e.g. set() constructors) but not others (e.g. C-style formatted strings replaced by format() in some cases).

I could agree for a merge in the develop branch for a limited set of cases (set, super, ...).

Thank you

**Comment by kloczek** [comment]
> Sorry but too many changes in so many files to be merged in the master branch.

All those changes has been generated automatically by `pyupgrade --py38-plus`.
You can install `pyupgrade` and execute `find . -name\*.py | xargs pyupgrade --py38-plus` and you will have exactly the same patch.

**Comment by brunato** [comment]
> > Sorry but too many changes in so many files to be merged in the master branch.
> 
> All those changes has been generated automatically by `pyupgrade --py38-plus`. You can install `pyupgrade` and execute `find . -name\*.py | xargs pyupgrade --py38-plus` and you will have exactly the same patch.

I understood that, but in development, not in master branch. 

I saw that _pyupgrade_ doesn't have so many exception options, anyway i will try it during development.

Dropping Python 3.7 doesn't mean necessarily that all the codebase is Py38+. In this case the compatibility is dropped mainly by the usage of protocols defined in the base package _elementpath_.

Thank you

**Comment by kloczek** [comment]
OK I understand.
You know what to do and how.
Just please do that when you will have time.

**Comment by brunato** [comment]
Tested on develop. Two things:

1.  The code produced with `pyupgrade --py38-plus` is exactly the same produced with `pyupgrade --py37-plus`
2.  Some strings are not translated neither if it's possible, maybe pyupgrade _gets_ confused sometimes when the value includes quotes or round brackets.

**Comment by brunato** [comment]
Also found a bug applying to a module in *elementpath*. A _for-yield_ is replaced with a `yield from` despite the variable is an instance attribute:

```diff
diff --git a/elementpath/xpath_context.py b/elementpath/xpath_context.py
index 3b16ee9..483bb85 100644
--- a/elementpath/xpath_context.py
+++ b/elementpath/xpath_context.py
@@ -386,8 +386,7 @@ class XPathContext:
             status = self.item, self.axis
             self.axis = 'attribute'
 
-            for self.item in self.item.attributes:
-                yield self.item
+            yield from self.item.attributes
 
             self.item, self.axis = status
```

**Comment by kloczek** [comment]
> Also found a bug applying to a module in _elementpath_. A _for-yield_ is replaced with a `yield from` despite the variable is an instance attribute:

Just open the ticket in `pyupgrade`.

**Pull request closed without merging**
