### PR TITLE
B121

### PR DESCRIPTION
**Pull request by danifus**
Fix for #121

### CODE REVIEW

**Comment by danifus** [comment]
Hi,

Me again :) Hope you don't mind all my attention at the moment :p

I read a lot zipped files and was having problems processing the xml directly from a file obj opened from a `ZipFile`. This patch fixes processing files where `name` doesn't point to a file on disk and possibly makes it a bit more secure.

From one of the commit msgs:

The fix changes how the `name` and `url` from file object attrs are used.

These attrs shouldn't be used to reopen the file object as:
- they may not reflect the original file or resource (file objects opened from a zipfile will have a name that doesn't correspond to any file on disk).
- Depending on how the fid was opened, these attrs could be crafted to read arbitrary files from disk. If the creator of a .zip gives a file inside the zip file a path of `/etc/passwd` we may end up opening that file.

Instead of reopening the file, we keep track of the file object and seek to the beginning of the file. This means (for most operations) the file object must be seekable. On Python 2 urlopen returns an unseekable object for 'file://' paths. One test had to be skipped in Python 2 for this reason.

Thanks,
Dan

**Comment by brunato** [comment]
Hi,
this has to be tested in all the different systems (Windows, MacOS, Linux) because path representation may differs. Also I take time to analize this after completion of XSD 1.1 validator, that I want to add into the next release.
Thanks

**Comment by danifus** [comment]
Thanks for looking into this.

The change shouldn't impact any paths that have been opened. It actually removes some instances where files were being opened and replaces them with `seek()`. There may need to be some documentation saying that reading from a file object requires it to be seekable.

I understand that it can take some time to test it properly, particularly with file operations :)

Let me know if you would like me to do any changes to the patch.

Thanks again,
Dan

**Comment by danifus** [comment]
Hi,

Thanks for merging!

Yeah, I think that is a pretty good compromise.

Thanks!

**Comment by brunato** [comment]
Hi @danifus ,

the new release v1.0.16 is available. I reworked the *XmlResource* class to use a smaller set of attributes in order to simplify the code. I've removed `_document` and `_fid`, substituted in their roles by the usage of `source` attribute (in the document property for the first and in resource open/seek for the second). This should be equivalent to the previous code but a bit simpler.

Bye
Davide

**Comment by brunato** [comment]
To be more precise: the *XMLResource* of v1.0.16 behaves as the version proposed with this PR but with less code (less attributes). The attribute *_fid* is not necessary because in the effective cases it's simply a duplicate of the attribute *source*.

**Pull request merged**
