### PR TITLE
Fix xmlschema-validate missing arguments

### PR DESCRIPTION
**Pull request by lukasz-mitka**
Version and locations arguments were not used.

Didn't check if it's working. Leaving it up to you @brunato.

### CODE REVIEW

**Comment by lukasz-mitka** [comment]
This PR could also use updating test cases.

**Comment by brunato** [comment]
Hi,
the cli interface is still not tested as it should, so missing arguments like that can happen. The runtime tests pass, but the CI fails with the flake8 tests. If you fix the linting error then i could merge without failures. 

Thanks

**Comment by brunato** [comment]
There are two linting errors to fix ...
```
xmlschema/cli.py:243:1: W293 blank line contains whitespace
xmlschema/cli.py:245:1: W293 blank line contains whitespace
2     W293 blank line contains whitespace
Error: Process completed with exit code 1.
```

**Comment by lukasz-mitka** [comment]
Thank you @brunato!

**Comment by lukasz-mitka** [comment]
@brunato any chances for a release?

**Comment by brunato** [comment]
In 4-5 days, after complete type hints on public API.

**Comment by brunato** [comment]
Hi, @lukasz-mitka, v1.8.0 is out ...

**Pull request merged**
